# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ab63de2c5ceeb085f25f5f75bd6c80476cca73743e40f9dffc1cb0bf10dcd7e87283a8908ec5a9647dd2bd567926939430e274b41b39af668e212b6677547c2

test:
  secret_key_base: 2ba83baddfbb9f886e7c9778b7f316cbb8a60286c6c852a02b3383ea817172c7d3d9c0ea6a6bcf0cf7997474416de333ed018f2ead65bab3d8f4112a1b0805c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
